# Default values for proglog.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: koneal2013/proglog
  tag: v0.0.10
  pullPolicy: IfNotPresent
serfPort: 8401
rpcPort: 8400
replicas: 3
storage: 1Gi